const stages={source:{name:'SOURCE',desc:'Ore intake capacity. The slowest stage limits the entire line.',base:1,cost:8,costGrowth:1.18,growth:1.11,level:0},process:{name:'PROCESS',desc:'Arc furnace throughput. Heat treatment turns raw ore into usable stock.',base:1,cost:8.6,costGrowth:1.18,growth:1.11,level:0},transfer:{name:'TRANSFER',desc:'Conveyor throughput. Material waiting on belts is production you do not own.',base:1,cost:8.2,costGrowth:1.18,growth:1.11,level:0},assembly:{name:'ASSEMBLY',desc:'Press-line throughput. Finished output cannot exceed assembly capacity.',base:1,cost:9,costGrowth:1.18,growth:1.11,level:0},power:{name:'POWER',desc:'Turbine support capacity. Every stage is capped by available industrial power.',base:6,cost:10,costGrowth:1.20,growth:1.18,level:0}};
const milestones=[{t:75,target:4,label:'INTAKE STABLE'},{t:150,target:14,label:'HEAT ONLINE'},{t:225,target:30,label:'LINE SYNCHRONIZED'},{t:300,target:52,label:'FINAL DIRECTIVE'}];
let credits=20,gameTime=0,speed=1,selected='source',overclockUntil=0,overclockReady=0,nextModule=34,moduleBonus=1,ended=false,last=performance.now();
const fmt=n=>n<10?n.toFixed(2):n<100?n.toFixed(1):Math.floor(n).toLocaleString();
function cap(id){let s=stages[id],v=s.base*Math.pow(s.growth,s.level);if(id===bottleneckRaw()&&gameTime<overclockUntil)v*=1.3;return v*moduleBonus}
function bottleneckRaw(){return Object.keys(stages).reduce((a,b)=>stages[a].base*Math.pow(stages[a].growth,stages[a].level)<=stages[b].base*Math.pow(stages[b].growth,stages[b].level)?a:b)}
function throughput(){return Math.min(...Object.keys(stages).map(cap))}
function cost(id){let s=stages[id];return s.cost*Math.pow(s.costGrowth,s.level)}
function log(msg){const box=document.getElementById('logLines');let d=document.createElement('div');d.className='log-line';d.innerHTML=`<b>${String(Math.floor(gameTime)).padStart(3,'0')}s</b> // ${msg}`;box.prepend(d);while(box.children.length>5)box.lastChild.remove()}
function renderMilestones(){const box=document.getElementById('milestoneList');box.innerHTML='';milestones.forEach((m,i)=>{let done=gameTime>=m.t&&throughput()>=m.target,current=gameTime<m.t&&(i===0||gameTime>=milestones[i-1].t);let row=document.createElement('div');row.className='milestone-row '+(done?'done':current?'current':'');row.innerHTML=`<i>${done?'✓':i+1}</i><div><strong>${m.label}</strong><small>${m.target}/s @ ${m.t}s</small></div><em>${gameTime>=m.t?(done?'CLEAR':'MISS'):'PENDING'}</em>`;box.append(row)})}
function select(id){selected=id;document.querySelectorAll('.machine').forEach(x=>x.classList.toggle('selected',x.dataset.id===id));let s=stages[id];document.getElementById('selectedName').textContent=s.name;document.getElementById('selectedDesc').textContent=s.desc;render()}
function upgrade(){if(ended)return;let c=cost(selected);if(credits<c)return;credits-=c;stages[selected].level++;log(`${stages[selected].name} upgraded to LV ${stages[selected].level}`);render()}
function pulse(){if(ended||gameTime<overclockReady)return;overclockUntil=gameTime+4;overclockReady=gameTime+12;log(`OVERCLOCK routed to ${stages[bottleneckRaw()].name}`);render()}
function recoverModule(){const modules=[['Refined Bearings',1.035,'throughput +3.5%'],['Thermal Recirculator',1.05,'throughput +5.0%'],['Prototype Servo Grid',1.075,'throughput +7.5%']];let r=Math.random(),m=r<.70?modules[0]:r<.94?modules[1]:modules[2];moduleBonus*=m[1];document.getElementById('moduleName').textContent=m[0];document.getElementById('moduleEffect').textContent=m[2]+' // auto-equipped';log(`module recovered: ${m[0]}`);nextModule=gameTime+28+Math.random()*32}
function render(){let tp=throughput(),b=bottleneckRaw(),remaining=Math.max(0,300-gameTime);document.getElementById('throughput').textContent=fmt(tp);document.getElementById('credits').textContent=fmt(credits);document.getElementById('clock').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(Math.floor(remaining%60)).padStart(2,'0')}`;let pct=Math.min(100,tp/52*100);document.getElementById('directiveFill').style.width=pct+'%';document.getElementById('directivePct').textContent=Math.floor(pct)+'%';document.getElementById('bottleneckLabel').textContent=`${stages[b].name} // ${fmt(cap(b))}/s`;document.querySelectorAll('.machine').forEach(el=>{let id=el.dataset.id,s=stages[id];el.classList.toggle('bottleneck',id===b);el.classList.toggle('level-high',s.level>=6);el.querySelector('strong').textContent=fmt(cap(id));el.querySelector('em').textContent='LV '+s.level});let s=stages[selected];document.getElementById('selectedCap').textContent=fmt(cap(selected))+'/s';document.getElementById('selectedCost').textContent=fmt(cost(selected));document.getElementById('upgradeBtn').disabled=credits<cost(selected)||ended;let oc=document.getElementById('overclock'),ready=Math.max(0,overclockReady-gameTime);oc.classList.toggle('cooldown',ready>0);oc.querySelector('strong').textContent=ready>0?ready.toFixed(1)+'s':'READY';renderMilestones()}
function tick(now){let real=Math.min(.25,(now-last)/1000);last=now;if(!document.hidden&&!ended){let dt=real*speed;gameTime+=dt;credits+=throughput()*dt*.55;if(gameTime>=nextModule)recoverModule();if(gameTime>=300){ended=true;let win=throughput()>=52;log(win?'DIRECTIVE ACHIEVED — transfer to prestige':'DIRECTIVE FAILED — salvage protocol armed');document.querySelector('.status span').textContent=win?'DIRECTIVE CLEAR':'SALVAGE';document.querySelector('.status').style.color=win?'var(--good)':'var(--danger)'}}render();requestAnimationFrame(tick)}
document.querySelectorAll('.machine').forEach(el=>el.addEventListener('click',()=>select(el.dataset.id)));document.getElementById('upgradeBtn').addEventListener('click',upgrade);document.getElementById('overclock').addEventListener('click',pulse);document.querySelectorAll('.speed button').forEach(btn=>btn.addEventListener('click',()=>{speed=Number(btn.dataset.speed);document.querySelectorAll('.speed button').forEach(x=>x.classList.toggle('active',x===btn));log(`simulation speed set to ×${speed}`)}));document.addEventListener('visibilitychange',()=>{last=performance.now();if(document.hidden)log('simulation paused: tab hidden')});log('Foundry-01 initialized');log('No offline progress. Factory runs only while visible.');select('source');requestAnimationFrame(tick);
