'use strict';
const E=window.InfiniteFoundryEngine;
const SAVE_KEY='infinite-foundry-save-v1';
const stageText={source:['SOURCE','Ore intake capacity. The slowest stage limits the entire line.'],process:['PROCESS','Arc furnace throughput. Heat treatment turns raw ore into usable stock.'],transfer:['TRANSFER','Conveyor throughput. Material waiting on belts is production you do not own.'],assembly:['ASSEMBLY','Press-line throughput. Finished output cannot exceed assembly capacity.'],power:['POWER','Turbine support capacity. Every stage is capped by available industrial power.']};
let state=load()||E.createState(E.baseMeta(Date.now()));
let selected='source',last=performance.now(),lastSaveReal=performance.now(),lastResultKey='',lastEventSeq=state.cycle.events?.at(-1)?.seq||0;
const $=id=>document.getElementById(id),fmt=n=>n<10?n.toFixed(2):n<100?n.toFixed(1):Math.floor(n).toLocaleString();
function load(){let raw=localStorage.getItem(SAVE_KEY),s=raw&&E.deserialize(raw);return s||null}
function save(){localStorage.setItem(SAVE_KEY,E.serialize(state));lastSaveReal=performance.now();$('saveState').textContent='SAVED'}
function log(msg){let box=$('logLines'),d=document.createElement('div');d.className='log-line';d.innerHTML=`<b>${String(Math.floor(state.cycle.time)).padStart(3,'0')}s</b> // ${msg}`;box.prepend(d);while(box.children.length>6)box.lastChild.remove()}
function processEvents(){for(const e of state.cycle.events||[]){if(e.seq<=lastEventSeq)continue;lastEventSeq=e.seq;if(e.type==='moduleRecovered')log(`MODULE ${e.rarity}: ${e.name} // ${e.action}`);else if(e.type==='directiveEvaluated')log(`${e.label}: ${e.clear?'CLEAR':'MISS'} ${fmt(e.value)}/${fmt(e.target)}/s`);else if(e.type==='automationUpgrade')log(`AUTOMATION MEMORY upgraded ${stageText[e.stage][0]} to LV ${e.level}`);else if(e.type==='metaUpgrade')log(`${String(e.upgrade).toUpperCase()} blueprint installed`);else if(e.type==='rebuild')log(`Foundry-${String(e.cycle).padStart(2,'0')} initialized with retained design knowledge`)}}
function select(id){selected=id;document.querySelectorAll('.machine').forEach(x=>x.classList.toggle('selected',x.dataset.id===id));$('selectedName').textContent=stageText[id][0];$('selectedDesc').textContent=stageText[id][1];render()}
function upgrade(){if(E.upgrade(state,selected)){log(`${stageText[selected][0]} upgraded to LV ${state.cycle.levels[selected]}`);save();render()}}
function pulse(){if(E.pulse(state)){render()}}
function setSpeed(v){state.cycle.speed=v;document.querySelectorAll('.speed button').forEach(x=>x.classList.toggle('active',Number(x.dataset.speed)===v));log(`simulation speed set to ×${v}`);save()}
function renderMilestones(){let box=$('milestoneList');box.innerHTML='';E.DIRECTIVES.forEach((m,i)=>{let r=state.cycle.checkpointResults.find(x=>x.index===i),current=!r&&state.cycle.time<m.t&&(i===0||state.cycle.time>=E.DIRECTIVES[i-1].t);let row=document.createElement('div');row.className='milestone-row '+(r?.clear?'done':current?'current':r?'miss':'');row.innerHTML=`<i>${r?.clear?'✓':i+1}</i><div><strong>${m.label}</strong><small>${m.target}/s @ ${m.t}s</small></div><em>${r?(r.clear?'CLEAR':'MISS'):'PENDING'}</em>`;box.append(row)})}
function renderModules(){let slots=E.upgradeEffects(state.meta).moduleSlots,box=$('moduleSlots');box.innerHTML='';for(let i=0;i<slots;i++){let m=state.cycle.modules[i],d=document.createElement('div');d.className='module-slot '+(m?'filled':'');d.innerHTML=m?`<span>${m.rarity}</span><strong>${m.name}</strong><small>${m.effect}</small>`:`<span>EMPTY BAY</span><strong>Awaiting recovery</strong><small>Modules auto-equip without pausing production.</small>`;box.append(d)}let latest=state.cycle.modules[state.cycle.modules.length-1];$('moduleName').textContent=latest?latest.name:'No module recovered';$('moduleEffect').textContent=latest?`${latest.effect} // installed`:'Automatic recovery. Production never pauses.'}
function renderPrestige(){let p=$('prestigePanel'),r=state.cycle.result;if(!r){p.hidden=true;return}p.hidden=false;let key=`${state.meta.cycle}:${r.win}:${r.blueprintsEarned}`;if(key!==lastResultKey){lastResultKey=key;log(r.win?'DIRECTIVE ACHIEVED — salvage complete':'DIRECTIVE FAILED — salvage complete');save()}$('resultTitle').textContent=r.win?'DIRECTIVE ACHIEVED':'DIRECTIVE FAILED';$('resultTitle').className=r.win?'win':'fail';$('resultSummary').textContent=`Final sustained throughput ${fmt(r.average)}/s. Salvaged +${r.blueprintsEarned} Blueprint.`;$('blueprints').textContent=state.meta.blueprints;$('cycleNo').textContent=state.meta.cycle+1;document.querySelectorAll('[data-meta-upgrade]').forEach(btn=>{let id=btn.dataset.metaUpgrade,lv=state.meta.upgrades[id],costs=E.UPGRADE_COSTS[id],c=costs[lv];btn.querySelector('b').textContent=`LV ${lv}`;btn.querySelector('em').textContent=c==null?'MAX':`${c} BP`;btn.disabled=c==null||state.meta.blueprints<c})}
function render(){processEvents();let era=E.currentEra(state),tp=E.throughput(state),b=E.rawBottleneck(state),remaining=Math.max(0,E.DIRECTIVES.at(-1).t-state.cycle.time);$('eraLabel').textContent=`${era.name} // DIRECTIVE 001`;$('foundryTitle').textContent=`Foundry-${String(state.meta.cycle).padStart(2,'0')} / ${era.site}`;$('throughput').textContent=fmt(tp);$('credits').textContent=fmt(state.cycle.credits);$('clock').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(Math.floor(remaining%60)).padStart(2,'0')}`;$('cycleBadge').textContent=`CYCLE ${String(state.meta.cycle).padStart(2,'0')}`;$('bpBadge').textContent=`BP ${state.meta.blueprints}`;let pct=Math.min(100,E.sustainedAverage(state,30)/52*100);$('directiveFill').style.width=pct+'%';$('directivePct').textContent=Math.floor(pct)+'%';$('bottleneckLabel').textContent=`${stageText[b][0]} // ${fmt(E.stageCapacity(state,b))}/s`;document.querySelectorAll('.machine').forEach(el=>{let id=el.dataset.id,lv=state.cycle.levels[id];el.classList.toggle('bottleneck',id===b);el.classList.toggle('level-high',lv>=6);el.querySelector('strong').textContent=fmt(E.stageCapacity(state,id));el.querySelector('em').textContent='LV '+lv});$('selectedCap').textContent=fmt(E.stageCapacity(state,selected))+'/s';$('selectedCost').textContent=fmt(E.cost(state,selected));$('upgradeBtn').disabled=!E.canUpgrade(state,selected);let ready=Math.max(0,state.cycle.overclockReady-state.cycle.time),oc=$('overclock');oc.classList.toggle('cooldown',ready>0||state.cycle.ended);oc.querySelector('strong').textContent=state.cycle.ended?'CYCLE END':ready>0?ready.toFixed(1)+'s':'READY';renderMilestones();renderModules();renderPrestige();document.querySelector('.status span').textContent=state.cycle.ended?(state.cycle.result.win?'DIRECTIVE CLEAR':'SALVAGE'):'ONLINE';document.querySelector('.status').classList.toggle('failed',state.cycle.ended&&!state.cycle.result.win);$('saveState').textContent=performance.now()-lastSaveReal<1500?'SAVED':'AUTO-SAVE'}
function buyMeta(id){if(E.buyMetaUpgrade(state,id)){save();render()}}
function restart(){state=E.restart(state);lastResultKey='';lastEventSeq=0;last=performance.now();save();select('source');render()}
function tick(now){let real=Math.min(.25,(now-last)/1000);last=now;if(!document.hidden&&!state.cycle.ended){E.advance(state,real*state.cycle.speed);if(now-lastSaveReal>5000)save()}render();requestAnimationFrame(tick)}
document.querySelectorAll('.machine').forEach(el=>el.addEventListener('click',()=>select(el.dataset.id)));$('upgradeBtn').addEventListener('click',upgrade);$('overclock').addEventListener('click',pulse);document.querySelectorAll('.speed button').forEach(btn=>btn.addEventListener('click',()=>setSpeed(Number(btn.dataset.speed))));document.querySelectorAll('[data-meta-upgrade]').forEach(btn=>btn.addEventListener('click',()=>buyMeta(btn.dataset.metaUpgrade)));$('restartBtn').addEventListener('click',restart);$('manualSave').addEventListener('click',save);$('resetSave').addEventListener('click',()=>{if(confirm('Erase all Infinite Foundry progress?')){localStorage.removeItem(SAVE_KEY);state=E.createState(E.baseMeta(Date.now()));save();location.reload()}});document.addEventListener('visibilitychange',()=>{last=performance.now();if(document.hidden){save();log('simulation paused: tab hidden')}else log('simulation resumed: no catch-up applied')});window.addEventListener('beforeunload',save);
log(`Foundry-${String(state.meta.cycle).padStart(2,'0')} online`);log('No offline progress. Factory runs only while visible.');setSpeed(state.cycle.speed||1);select('source');requestAnimationFrame(tick);
