(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports) module.exports=api;
  else root.InfiniteFoundryEngine=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const VERSION=2, STEP=0.05;
  const STAGE_DEFS={source:{name:'SOURCE',base:1.2,cost:8,costGrowth:1.18,growth:1.11},process:{name:'PROCESS',base:1,cost:9,costGrowth:1.18,growth:1.11},transfer:{name:'TRANSFER',base:.9,cost:10,costGrowth:1.18,growth:1.11},assembly:{name:'ASSEMBLY',base:.8,cost:11,costGrowth:1.18,growth:1.11},power:{name:'POWER',base:6,cost:10,costGrowth:1.20,growth:1.18}};
  const DIRECTIVES=[{t:75,target:4,label:'INTAKE STABLE'},{t:150,target:14,label:'HEAT ONLINE'},{t:225,target:30,label:'LINE SYNCHRONIZED'},{t:300,target:52,label:'FINAL DIRECTIVE'}];
  const MODULES=[{id:'bearings',name:'Refined Bearings',rarity:'COMMON',min:.04,max:.08},{id:'thermal',name:'Thermal Recirculator',rarity:'REFINED',min:.08,max:.15},{id:'servo',name:'Prototype Servo Grid',rarity:'PROTOTYPE',min:.18,max:.30}];
  const UPGRADE_COSTS={efficiency:[8,18,36,70],capital:[6,16,34],automation:[10,24,50],moduleBay:[14,38]};
  function xorshift32(seed){let x=(seed>>>0)||0x9e3779b9;return function(){x^=x<<13;x^=x>>>17;x^=x<<5;return (x>>>0)/4294967296}}
  function hashSeed(seed,cycle){let x=(seed>>>0)^(Math.imul(cycle+1,0x9e3779b1)>>>0);x^=x>>>16;x=Math.imul(x,0x7feb352d);x^=x>>>15;return x>>>0}
  function baseMeta(seed){return {blueprints:0,cycle:1,seed:(seed>>>0)||0x13579bdf,upgrades:{efficiency:0,capital:0,automation:0,moduleBay:0},discoveredModules:[],bestThroughput:0,totalOutput:0,successfulCycles:0}}
  function upgradeEffects(meta){return {capacity:1+0.08*meta.upgrades.efficiency,startCredits:20+8*meta.upgrades.capital,moduleSlots:2+meta.upgrades.moduleBay,autoBudget:meta.upgrades.automation}}
  function createState(meta){meta=meta?JSON.parse(JSON.stringify(meta)):baseMeta(Date.now());let e=upgradeEffects(meta);let state={version:VERSION,meta,cycle:{time:0,accumulator:0,credits:e.startCredits,levels:{source:0,process:0,transfer:0,assembly:0,power:0},speed:1,overclockUntil:0,overclockReady:0,nextModuleAt:0,modulePityAt:0,modules:[],throughputSamples:[],output:0,ended:false,result:null,checkpointResults:[],lastCheckpointIndex:-1,rngState:hashSeed(meta.seed,meta.cycle),events:[],nextEventSeq:1,automationCheckAt:75}};emitEvent(state,'cycleStarted',{cycle:meta.cycle});return state}
  function emitEvent(state,type,data={}){let e={seq:state.cycle.nextEventSeq++,time:state.cycle.time,type,...data};state.cycle.events.push(e);while(state.cycle.events.length>48)state.cycle.events.shift();return e}
  function rngFor(state){let r=xorshift32(state.cycle.rngState),v=r();state.cycle.rngState=Math.floor(r()*4294967295)>>>0;return v}
  function moduleMultiplier(state,id){return state.cycle.modules.reduce((mult,x)=>x.target===id?mult*x.mult:mult,1)}
  function growthSeries(growth,levels){return levels<=0?1:(Math.pow(growth,levels)-1)/(growth-1)+1}
  function stageCapacityNoModule(state,id){let d=STAGE_DEFS[id],e=upgradeEffects(state.meta);return d.base*growthSeries(d.growth,state.cycle.levels[id])*e.capacity}
  function rawBottleneck(state){let best='source',v=Infinity;for(let id of Object.keys(STAGE_DEFS)){let c=stageCapacityNoModule(state,id);if(c<v-1e-9){v=c;best=id}}return best}
  function stageCapacity(state,id,includeOverclock=true){let v=stageCapacityNoModule(state,id)*moduleMultiplier(state,id);if(includeOverclock&&id===rawBottleneck(state)&&state.cycle.time<state.cycle.overclockUntil)v*=1.3;return v}
  function throughput(state){return Math.min(...Object.keys(STAGE_DEFS).map(id=>stageCapacity(state,id,true)))}
  function cost(state,id){let d=STAGE_DEFS[id];return d.cost*Math.pow(d.costGrowth,state.cycle.levels[id])}
  function canUpgrade(state,id){return !state.cycle.ended&&state.cycle.credits+1e-9>=cost(state,id)}
  function upgrade(state,id){if(!STAGE_DEFS[id]||!canUpgrade(state,id))return false;state.cycle.credits-=cost(state,id);state.cycle.levels[id]++;return true}
  function pulse(state){if(state.cycle.ended||state.cycle.time+1e-9<state.cycle.overclockReady)return false;let target=rawBottleneck(state);state.cycle.overclockUntil=state.cycle.time+4;state.cycle.overclockReady=state.cycle.time+12;emitEvent(state,'overclock',{stage:target});return true}
  function scheduleFirstModule(state){if(state.cycle.nextModuleAt>0)return;state.cycle.nextModuleAt=28+rngFor(state)*28;state.cycle.modulePityAt=80}
  function drawModule(state){let r=rngFor(state),template=r<.70?MODULES[0]:r<.94?MODULES[1]:MODULES[2],boost=template.min+rngFor(state)*(template.max-template.min),targets=['source','process','transfer','assembly'],target=targets[Math.floor(rngFor(state)*targets.length)],m={...template,mult:1+boost,target,effect:`${STAGE_DEFS[target].name} +${(boost*100).toFixed(1)}%`},slots=upgradeEffects(state.meta).moduleSlots,action='equipped',replaced=null;if(state.cycle.modules.length<slots)state.cycle.modules.push({...m});else{let weakest=0;for(let i=1;i<state.cycle.modules.length;i++)if(state.cycle.modules[i].mult<state.cycle.modules[weakest].mult)weakest=i;if(m.mult>state.cycle.modules[weakest].mult){replaced=state.cycle.modules[weakest].id;state.cycle.modules[weakest]={...m};action='replaced'}else action='catalogued'}if(!state.meta.discoveredModules.includes(m.id))state.meta.discoveredModules.push(m.id);state.cycle.nextModuleAt=state.cycle.time+28+rngFor(state)*32;state.cycle.modulePityAt=state.cycle.time+80;emitEvent(state,'moduleRecovered',{moduleId:m.id,name:m.name,rarity:m.rarity,effect:m.effect,target:m.target,action,replaced});return m}
  function sustainedAverage(state,seconds=30){let cutoff=Math.max(0,state.cycle.time-seconds),s=state.cycle.throughputSamples.filter(x=>x.t>=cutoff);if(!s.length)return throughput(state);let weighted=0,total=0;for(let i=1;i<s.length;i++){let dt=s[i].t-s[i-1].t;weighted+=s[i-1].v*dt;total+=dt}return total>0?weighted/total:s[s.length-1].v}
  function salvageBlueprints(state){let cleared=state.cycle.checkpointResults.filter(x=>x.clear).length,ratio=Math.min(1,sustainedAverage(state,30)/DIRECTIVES[3].target);return 2+2*cleared+Math.floor(3*Math.sqrt(Math.max(0,ratio)))}
  function evaluateCheckpoints(state){while(state.cycle.lastCheckpointIndex+1<DIRECTIVES.length&&state.cycle.time+1e-9>=DIRECTIVES[state.cycle.lastCheckpointIndex+1].t){let i=++state.cycle.lastCheckpointIndex,d=DIRECTIVES[i],v=i===DIRECTIVES.length-1?sustainedAverage(state,30):throughput(state),clear=v+1e-9>=d.target;state.cycle.checkpointResults.push({index:i,time:d.t,target:d.target,value:v,clear});emitEvent(state,'directiveEvaluated',{index:i,label:d.label,target:d.target,value:v,clear})}}
  function runAutomation(state){let lv=state.meta.upgrades.automation;if(lv<=0||state.cycle.ended)return;while(state.cycle.time+1e-9>=state.cycle.automationCheckAt){let threshold=[Infinity,1.8,1.5,1.3][Math.min(3,lv)]||1.3,id=rawBottleneck(state),c=cost(state,id);if(state.cycle.credits+1e-9>=c*threshold&&upgrade(state,id))emitEvent(state,'automationUpgrade',{stage:id,level:state.cycle.levels[id],cost:c});state.cycle.automationCheckAt+=10}}
  function finishCycle(state){if(state.cycle.ended)return;let avg=sustainedAverage(state,30),win=avg+1e-9>=DIRECTIVES[3].target,bp=salvageBlueprints(state);state.cycle.ended=true;state.cycle.result={win,average:avg,blueprintsEarned:bp};state.meta.blueprints+=bp;state.meta.bestThroughput=Math.max(state.meta.bestThroughput,avg);state.meta.totalOutput+=state.cycle.output;if(win)state.meta.successfulCycles++;emitEvent(state,'cycleEnded',{win,average:avg,blueprintsEarned:bp})}
  function step(state,dt=STEP){if(state.cycle.ended)return;scheduleFirstModule(state);let end=Math.min(DIRECTIVES[3].t,state.cycle.time+dt),actual=end-state.cycle.time;if(actual<=0){finishCycle(state);return}let tp=throughput(state);state.cycle.credits+=tp*actual;state.cycle.output+=tp*actual;state.cycle.time=end;state.cycle.throughputSamples.push({t:state.cycle.time,v:tp});while(state.cycle.throughputSamples.length>800)state.cycle.throughputSamples.shift();if(state.cycle.time+1e-9>=state.cycle.nextModuleAt||state.cycle.time+1e-9>=state.cycle.modulePityAt)drawModule(state);runAutomation(state);evaluateCheckpoints(state);if(state.cycle.time+1e-9>=DIRECTIVES[3].t)finishCycle(state)}
  function advance(state,gameSeconds){let total=state.cycle.accumulator+Math.max(0,gameSeconds),n=Math.floor(total/STEP+1e-9);state.cycle.accumulator=total-n*STEP;for(let i=0;i<n&&!state.cycle.ended;i++)step(state,STEP);return n}
  function buyMetaUpgrade(state,id){let arr=UPGRADE_COSTS[id],lv=state.meta.upgrades[id];if(!arr||lv>=arr.length)return false;let c=arr[lv];if(state.meta.blueprints<c)return false;state.meta.blueprints-=c;state.meta.upgrades[id]++;emitEvent(state,'metaUpgrade',{upgrade:id,level:state.meta.upgrades[id],cost:c});return true}
  function restart(state){let meta=JSON.parse(JSON.stringify(state.meta));meta.cycle++;let next=createState(meta);emitEvent(next,'rebuild',{cycle:meta.cycle});return next}
  function serialize(state){return JSON.stringify({version:VERSION,savedAt:Date.now(),state})}
  function normalizeState(s){if(!s||!s.meta||!s.cycle)return null;s.version=VERSION;s.cycle.accumulator=0;if(!Array.isArray(s.cycle.events))s.cycle.events=[];let maxSeq=s.cycle.events.reduce((m,e)=>Math.max(m,Number(e.seq)||0),0);s.cycle.nextEventSeq=Math.max(Number(s.cycle.nextEventSeq)||1,maxSeq+1);if(!Number.isFinite(s.cycle.automationCheckAt))s.cycle.automationCheckAt=Math.max(75,75+10*Math.floor(Math.max(0,s.cycle.time-75)/10));if(!Number.isFinite(s.cycle.rngState))s.cycle.rngState=hashSeed(s.meta.seed,s.meta.cycle);return s}
  function deserialize(raw){try{let p=typeof raw==='string'?JSON.parse(raw):raw;if(!p||!p.state||!Number.isFinite(Number(p.version))||Number(p.version)>VERSION)return null;return normalizeState(p.state)}catch(e){return null}}
  return {VERSION,STEP,STAGE_DEFS,DIRECTIVES,MODULES,UPGRADE_COSTS,baseMeta,createState,upgradeEffects,stageCapacity,rawBottleneck,moduleMultiplier,throughput,cost,canUpgrade,upgrade,pulse,sustainedAverage,salvageBlueprints,advance,buyMetaUpgrade,restart,serialize,deserialize};
});
