const assert=require('assert');
const E=require('../engine.js');
assert.equal(E.VERSION,5);assert.equal(Object.keys(E.ERA_DEFS).length,7);assert.equal(E.currentEra(E.baseMeta(123)).id,1);
function runWithChunks(chunks){const s=E.createState(E.baseMeta(123456));for(const chunk of chunks)E.advance(s,chunk);return s}
const a=runWithChunks(Array(300).fill(1)),b=runWithChunks(Array(75).fill(4));assert(Math.abs(a.cycle.time-b.cycle.time)<1e-9);assert(Math.abs(a.cycle.credits-b.cycle.credits)<1e-6);assert.deepStrictEqual(a.cycle.moduleInventory.map(x=>[x.id,x.target,x.mult]),b.cycle.moduleInventory.map(x=>[x.id,x.target,x.mult]));
let s=E.createState(E.baseMeta(7));assert(E.upgrade(s,'source'));let loaded=E.deserialize(E.serialize(s));assert(loaded&&loaded.cycle.levels.source===1);E.advance(loaded,300);assert(loaded.cycle.ended&&loaded.cycle.result);assert(loaded.meta.blueprints>=2);let restarted=E.restart(loaded);assert.equal(restarted.meta.cycle,2);assert.equal(restarted.meta.blueprints,loaded.meta.blueprints);assert.equal(restarted.cycle.moduleInventory.length,0);
let m=E.createState(E.baseMeta(8));m.meta.blueprints=8;assert(E.buyMetaUpgrade(m,'efficiency'));assert.equal(m.meta.upgrades.efficiency,1);
let mods=E.createState(E.baseMeta(1234));mods.meta.introSeen=true;E.advance(mods,E.currentEra(mods).duration*.75);assert(!mods.cycle.ended,'module equip fixture must remain inside an active run');assert(mods.cycle.moduleInventory.length>=2,'modules should be recovered');const candidate=mods.cycle.moduleInventory.find(x=>!mods.cycle.modules.some(y=>y?.uid===x.uid))||mods.cycle.moduleInventory.at(-1);assert(candidate);const before=mods.cycle.modules.map(x=>x?.uid||null);assert(E.equipModule(mods,candidate.uid,0)||before[0]===candidate.uid);assert(mods.cycle.modules[0]);
let legacy=E.createState(E.baseMeta(10));legacy.version=4;delete legacy.meta.introSeen;legacy.cycle.time=10;delete legacy.cycle.moduleInventory;delete legacy.cycle.nextModuleSerial;legacy.cycle.modules=[{id:'bearings',name:'Refined Bearings',rarity:'COMMON',mult:1.05,target:'source',effect:'SOURCE +5.0%'}];let migrated=E.deserialize(JSON.stringify({version:4,state:legacy}));assert(migrated);assert.equal(migrated.meta.introSeen,true);assert(Array.isArray(migrated.cycle.moduleInventory)&&migrated.cycle.moduleInventory.length===1);assert(migrated.cycle.modules[0].uid);assert.equal(E.deserialize(JSON.stringify({version:E.VERSION+1,state:legacy})),null);
console.log('engine tests: ok');
