'use strict';
const assert=require('assert'),fs=require('fs');
const css=fs.readFileSync('playfeel-round7.css','utf8');
const loader=fs.readFileSync('playfeel-round5.js','utf8');
assert(loader.includes("['playfeel-round6.css','playfeel-round7.css']"),'Round 7 CSS must load after Round 6');
assert(css.includes('grid-template-columns:repeat(2,minmax(0,1fr))'),'phone production stages must use a 2-column layout');
assert(css.includes('.line>.belt{display:none}'),'full belt columns must not consume phone touch width');
assert(css.includes('min-width:44px'),'direct upgrade control must retain a 44px minimum width on phone');
assert(css.includes('min-height:136px'),'phone machine cards must preserve readable vertical space');
assert(css.includes('content:"→"')&&css.includes('content:"↓"'),'compact mobile production flow must remain visually legible');
assert(css.includes('max-width:calc(100% - 158px)'),'factory label must reserve horizontal space for the power machine');
console.log('playfeel round7 contract tests passed');
