'use strict';
const E=require('../../engine.js');
globalThis.InfiniteFoundryEngine=E;
const M=require('../../era-mechanics.js');

const MODES={
  optimal:{minDelay:1,maxDelay:1,pulseChance:1,maxBuys:24},
  attentive:{minDelay:7,maxDelay:12,pulseChance:.82,maxBuys:12},
  relaxed:{minDelay:12,maxDelay:20,pulseChance:.52,maxBuys:8}
};
function rng(seed){let x=(seed>>>0)||0x9e3779b9;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function delayFor(r,mode){const d=MODES[mode]||MODES.attentive;return d.minDelay+r()*(d.maxDelay-d.minDelay)}
function decide(state,r,mode){const d=MODES[mode]||MODES.attentive;if(r()<d.pulseChance&&E.pulse(state))M.afterPulse(state);let buys=0;while(buys<d.maxBuys&&!state.cycle.ended){const id=E.rawBottleneck(state),price=E.cost(state,id);if(!E.canUpgrade(state,id))break;const was=E.rawBottleneck(state)===id;if(!E.upgrade(state,id))break;M.afterUpgrade(state,id,price,was);buys++}return buys}
function playCycle(state,{mode='attentive',seed=1}={}){const r=rng(seed),era=E.currentEra(state);let nextDecision=0,decisions=0,buys=0;while(!state.cycle.ended){const remaining=era.duration-state.cycle.time;if(remaining<=1e-9){E.advance(state,.05);break}const step=Math.min(remaining,Math.max(.05,nextDecision-state.cycle.time));if(step>0)E.advance(state,step);if(state.cycle.ended)break;if(state.cycle.time+1e-9>=nextDecision){buys+=decide(state,r,mode);decisions++;nextDecision=state.cycle.time+delayFor(r,mode)}}return {state,decisions,buys,ratio:state.cycle.result.average/E.currentEra(state).targets[3]}}
function spendBlueprints(state){const order=['efficiency','capital','moduleBay','automation'];let changed=true,guard=0;while(changed&&guard++<32){changed=false;for(const id of order){if(E.buyMetaUpgrade(state,id)){changed=true;break}}}}
function spendPatents(state){let guard=0;while(state.meta.patents>0&&guard++<12){if(E.buyPatentUpgrade(state,'powerRouting'))continue;if(E.buyPatentUpgrade(state,'salvageTheory'))continue;break}}
function simulateRoute(seed,{mode='attentive',maxCycles=80}={}){let state=E.createState(E.baseMeta(seed)),cycles=0,totalGameTime=0;const attempts=Array(8).fill(0),firstAttemptWins=Array(8).fill(null),ratios=Array.from({length:8},()=>[]),decisions=Array(8).fill(0);while(!state.meta.endingUnlocked&&cycles<maxCycles){const era=state.meta.era;attempts[era]++;const out=playCycle(state,{mode,seed:(seed^Math.imul(cycles+1,0x45d9f3b))>>>0});cycles++;totalGameTime+=E.currentEra(state).duration;ratios[era].push(out.ratio);decisions[era]+=out.decisions;if(attempts[era]===1)firstAttemptWins[era]=!!state.cycle.result.win;const win=state.cycle.result.win;spendBlueprints(state);spendPatents(state);if(state.meta.endingUnlocked)break;state=E.restart(state,win&&E.canAdvanceEra(state))}return {seed,mode,finished:state.meta.endingUnlocked,cycles,totalGameTime,attempts:attempts.slice(1),firstAttemptWins:firstAttemptWins.slice(1),ratios:ratios.slice(1),decisions:decisions.slice(1),upgrades:{...state.meta.upgrades},patentUpgrades:{...state.meta.patentUpgrades}}}
function summarize(rows){const q=(a,p)=>{const v=[...a].sort((x,y)=>x-y);return v.length?v[Math.floor((v.length-1)*p)]:0};const era=Array.from({length:7},(_,i)=>{const first=rows.filter(r=>r.firstAttemptWins[i]!=null);const allRatios=rows.flatMap(r=>r.ratios[i]);return {era:i+1,firstAttemptClear:first.length?first.filter(r=>r.firstAttemptWins[i]).length/first.length:null,attemptP50:q(rows.map(r=>r.attempts[i]),.5),attemptP90:q(rows.map(r=>r.attempts[i]),.9),ratioP50:q(allRatios,.5),ratioP10:q(allRatios,.1)}});return {mode:rows[0]?.mode||'unknown',finishRate:rows.length?rows.filter(r=>r.finished).length/rows.length:0,cyclesP50:q(rows.map(r=>r.cycles),.5),cyclesP90:q(rows.map(r=>r.cycles),.9),era}}
module.exports={MODES,playCycle,simulateRoute,summarize};
if(require.main===module){const seeds=Math.max(6,Number(process.env.IF_HUMAN_SEEDS)||12),maxCycles=Math.max(10,Number(process.env.IF_HUMAN_MAX_CYCLES)||40);for(const mode of ['optimal','attentive','relaxed']){const rows=[];for(let i=1;i<=seeds;i++)rows.push(simulateRoute((0x7100000+i)>>>0,{mode,maxCycles}));console.log(JSON.stringify(summarize(rows),null,2))}}
